/**
 * Central SEO configuration. Safe to import from Server and Client Components.
 *
 * SITE_URL must be the canonical host that actually serves pages: the apex
 * domain (cvixeo.com) 308-redirects to www, so canonicals, hreflang, sitemap
 * and JSON-LD all point at www to avoid "canonical → redirect" signals.
 */
export const SITE_URL = "https://www.cvixeo.com";
export const SITE_NAME = "CVixeo";

export type Locale = "en" | "fr" | "nl";

/** Prefix an unlocalized path ("/pricing", "/", "/#faq") with the locale segment. */
export function localePath(lang: Locale, path: string): string {
  if (lang === "en") return path;
  if (path === "/") return `/${lang}`;
  if (path.startsWith("/#")) return `/${lang}${path.slice(1)}`;
  return `/${lang}${path}`;
}

/** Canonical + hreflang alternates for a route available in all three locales. */
export function localizedAlternates(lang: Locale, path: string) {
  const url = (l: Locale) => `${SITE_URL}${localePath(l, path)}`.replace(/\/$/, "") || SITE_URL;
  return {
    canonical: url(lang),
    languages: {
      en: url("en"),
      fr: url("fr"),
      nl: url("nl"),
      "x-default": url("en"),
    },
  };
}

export const OG_LOCALE: Record<Locale, string> = {
  en: "en_US",
  fr: "fr_FR",
  nl: "nl_BE",
};

/**
 * Spread into every page-level `openGraph` object. A page's `openGraph` replaces
 * the parent's entirely (no deep merge), which otherwise drops the share image
 * generated by app/opengraph-image.tsx, plus siteName and type.
 */
export const OG_DEFAULTS = {
  type: "website" as const,
  siteName: SITE_NAME,
  images: [
    {
      url: "/opengraph-image",
      width: 1200,
      height: 630,
      alt: "CVixeo — AI CV Builder & ATS Resume Optimizer",
    },
  ],
};

/** For private or utility pages (auth, onboarding, dashboard): crawlable but never indexed. */
export const NOINDEX = { index: false, follow: false } as const;
