"use client";

import { createContext, useContext, useState, useEffect } from "react";

type Lang = "en" | "fr";

interface LanguageContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
}

const LanguageContext = createContext<LanguageContextValue>({ lang: "en", setLang: () => {} });

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>("en");

  useEffect(() => {
    const stored = localStorage.getItem("cv-lang") as Lang | null;
    if (stored === "fr" || stored === "en") {
      setLangState(stored);
    } else {
      const browserFr = navigator.language.startsWith("fr");
      setLangState(browserFr ? "fr" : "en");
    }
  }, []);

  function setLang(l: Lang) {
    setLangState(l);
    localStorage.setItem("cv-lang", l);
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}

export const translations = {
  en: {
    // ── Navbar ──────────────────────────────────────────────────────────────
    nav: {
      features: "Features",
      pricing: "Pricing",
      careers: "Careers",
      contact: "Contact",
      signIn: "Sign in",
      getStarted: "Get started",
      myAccount: "My Account",
      myResumes: "My Resumes",
    },

    // ── Hero ─────────────────────────────────────────────────────────────────
    hero: {
      badge: "Cvixeo — Be seen. Be chosen.",
      headline1: "Land your dream job",
      headline2: "CVixeo",
      subtext:
        "Generate ATS-optimized, professionally crafted CVs in minutes. Match your CV to any job description and download beautiful PDFs instantly.",
      highlights: [
        "ATS-optimized in one click",
        "AI bullet point generation",
        "PDF export included",
      ],
      stats: [
        { value: "10,000+", label: "CVs created" },
        { value: "94%",     label: "ATS pass rate" },
        { value: "3×",      label: "More interviews" },
      ],
      ctaPrimary: "Build your CV free",
      ctaSecondary: "View pricing",
      noCard: "No credit card required · Free plan available",
      mock: {
        nav: ["Dashboard", "My CVs", "Templates", "Settings", "Support"],
        stats: [
          { label: "Total CVs",  value: "3" },
          { label: "Published",  value: "2" },
          { label: "Avg ATS",    value: "91%" },
          { label: "Plan",       value: "Pro ✨" },
        ],
        yourCVs:   "Your CVs",
        atsScore:  "ATS Score",
        published: "Published",
        draft:     "Draft",
        newCV:     "New CV",
      },
    },

    // ── Features ─────────────────────────────────────────────────────────────
    features: {
      sectionLabel: "Features",
      headline: "Everything you need to land the job",
      subtext:
        "From first draft to final PDF — Cvixeo handles the heavy lifting so you can focus on what matters.",
      items: [
        { title: "AI-Powered Generation",      description: "Describe your experience and let GPT-4 write a compelling, professional CV tailored to your target role." },
        { title: "ATS Optimization",           description: "Score your CV against Applicant Tracking Systems and get specific suggestions to pass automated screening." },
        { title: "Job Description Matching",   description: "Paste any job listing and get a match score plus a list of improvements to tailor your CV perfectly." },
        { title: "Beautiful Templates",        description: "Choose from professionally designed templates. Switch between styles instantly without losing your data." },
        { title: "One-Click PDF Export",       description: "Download pixel-perfect PDFs that look great on screen and in print. Pro plan removes watermarks." },
        { title: "Cover Letter Generator",     description: "Automatically generate personalized cover letters matched to specific job descriptions and companies." },
      ],
    },

    // ── Testimonials ─────────────────────────────────────────────────────────
    testimonials: {
      sectionLabel: "Testimonials",
      headline: "Loved by job seekers worldwide",
      items: [
        { name: "Sarah Chen",      role: "Software Engineer at Google",      avatar: "SC", content: "Cvixeo helped me land my dream job at Google. The ATS optimization feature was a game-changer — my CV was getting ignored before, but after the AI suggestions I started getting callbacks within days." },
        { name: "Marcus Johnson",  role: "Product Manager at Stripe",        avatar: "MJ", content: "I rewrote my CV 4 times before trying Cvixeo. The job description matching feature is incredible — it told me exactly which keywords I was missing and helped me tailor each application." },
        { name: "Elena Rodriguez", role: "UX Designer at Figma",             avatar: "ER", content: "The modern template is stunning. Multiple recruiters mentioned how professional my CV looked. The cover letter generator saved me hours per application." },
        { name: "David Park",      role: "Data Scientist at OpenAI",         avatar: "DP", content: "As someone who hates writing, the AI generation feature was perfect. I just filled in my experience and it turned my bullet points into compelling, professional descriptions." },
        { name: "Priya Patel",     role: "Marketing Lead at HubSpot",        avatar: "PP", content: "Worth every penny of the Pro plan. I upgraded within 10 minutes of trying the free plan — the unlimited CVs and PDF export are essential when you're actively job hunting." },
        { name: "James Williams",  role: "Backend Engineer at Vercel",       avatar: "JW", content: "The ATS score went from 42 to 91 after following Cvixeo's suggestions. I had 3 interviews scheduled within a week of updating my CV." },
      ],
    },

    // ── CTA ──────────────────────────────────────────────────────────────────
    cta: {
      headline:  "Ready to land your dream job?",
      subtext:   "Join 10,000+ professionals who have already leveled up their job search with Cvixeo. Start free, upgrade when you need.",
      primary:   "Get started for free",
      secondary: "See all plans",
      footnote:  "No credit card required · Cancel anytime · from €9/month",
    },

    // ── Footer ───────────────────────────────────────────────────────────────
    footer: {
      pricing:     "Pricing",
      features:    "Features",
      careers:     "Careers",
      signIn:      "Sign in",
      rights:      "All rights reserved.",
      product:     "Product",
      legal:       "Legal",
      about:       "About",
      privacy:     "Privacy Policy",
      terms:       "Terms of Use",
      cookies:     "Cookie Policy",
      legalNotice: "Legal Notice",
    },

    // ── Pricing page ─────────────────────────────────────────────────────────
    pricing: {
      back:             "Back",
      headline:         "Simple, transparent pricing",
      subtext:          "Start free. Try 7 days for €3.99, or subscribe for ongoing access.",
      moneyBack:        "Subscriptions include a 14-day money-back guarantee. No questions asked.",
      faqTitle:         "Frequently asked questions",
      // Card names
      freeName:         "Free",
      passName:         "7-Day Pass",
      monthlyName:      "Monthly Premium",
      annualName:       "Annual Premium",
      // Card descriptions
      freeDescription:  "Perfect for getting started",
      passDescription:  "Full access for 7 days",
      monthlyDescription: "For ongoing job seekers",
      annualDescription:  "Best value — save 25%",
      // Card features
      freeFeatures: [
        "Create a resume",
        "Edit sections",
        "Basic templates",
        "PDF Export",
      ],
      passFeatures: [
        "PDF export (no watermark)",
        "All Premium templates",
        "ATS optimization",
        "AI suggestions",
        "Customize for job postings",
        "Cover letter generation",
        "Resume import & improvement",
      ],
      monthlyFeatures: [
        "All Free plan features",
        "ATS Optimization",
        "Advanced AI Suggestions",
        "Automatic Experience Enhancement",
        "Customization based on job postings",
        "Cover letter generation",
        "Resume import & improvement",
      ],
      annualFeatures: [
        "All Premium features",
        "Save €36/year vs monthly",
      ],
      // CTA buttons
      freeCtaLabel:    "Get Started for Free",
      passCtaLabel:    "Get 7-Day Access — €3.99",
      monthlyCtaLabel: "Subscribe for €12/month",
      annualCtaLabel:  "Subscribe for €108/year",
      // Badges & labels
      passNew:         "Try it",
      mostPopular:     "Most Popular",
      bestValue:       "Best Value",
      saveBadge:       "Save 25%",
      perMonth:        "/month",
      passOnce:        "one-time",
      annualBilledAs:  "billed as €108/year",
      previewTitle:    "What you'll build",
      plansLabel:      "View plans",
      // Legacy keys kept for backward compat
      proDescription:  "For serious job seekers",
      billingMonthly:  "Monthly",
      billingAnnual:   "Annual",
      faqs: [
        { q: "What is the 7-Day Premium Pass?",                  a: "A one-time payment of €3.99 that unlocks all Premium features for 7 days. After 7 days, you automatically revert to the Free plan. Your CVs and data are always kept." },
        { q: "Can I cancel my subscription anytime?",            a: "Yes. Cancel your Premium subscription any time from your account settings. You retain Premium access until the end of your billing period." },
        { q: "What happens to my CVs if I downgrade?",           a: "Your CVs are always saved. On the Free plan, you can only actively edit 1 CV, but your others remain accessible in read-only mode." },
        { q: "What is the difference between monthly and annual?", a: "Monthly is €12/month. Annual is €9/month billed as €108/year — you save 25% compared to monthly billing." },
        { q: "What AI model powers the CV generation?",          a: "We use Claude by Anthropic for all AI features — a state-of-the-art model optimized for professional writing." },
        { q: "Are my CVs private?",                              a: "Absolutely. Your CVs are private by default. You can choose to generate a shareable link, but nothing is public unless you explicitly share it." },
      ],
    },

    // ── Contact page ────────────────────────────────────────────────────────
    contact: {
      title:    "Contact us",
      subtitle: "Have a question or need help? We're here for you.",
      form: {
        name:               "Your name",
        namePlaceholder:    "Jane Smith",
        email:              "Your email",
        emailPlaceholder:   "jane@example.com",
        subject:            "Subject",
        subjectPlaceholder: "How can we help you?",
        message:            "Message",
        messagePlaceholder: "Describe your question or issue in detail...",
        submit:             "Send message",
        submitting:         "Sending…",
        successTitle:       "Message sent!",
        successText:        "We'll get back to you within 24 hours.",
        errorText:          "Something went wrong. Please try again.",
      },
      support: {
        heading:       "We're here for you",
        subheading:    "Our team is dedicated to helping you succeed in your job search.",
        emailLabel:    "Support email",
        email:         "support@cvixeo.com",
        responseLabel: "Response time",
        responseTime:  "Within 24 hours",
        responseNote:  "Mon–Fri, 9 am–6 pm CET",
        reassurance:   "We read every message personally and respond as quickly as possible. No bots, no auto-replies — a real person will always get back to you.",
      },
      faq: {
        title: "Quick answers",
        items: [
          { q: "How do I cancel my subscription?",      a: "Go to Settings → Subscription in your dashboard and click Cancel. You keep Premium access until the end of your billing period." },
          { q: "My PDF export isn't working.",          a: "Make sure pop-ups are allowed for this site. The PDF opens in a new tab — save it via Ctrl+P → Save as PDF." },
          { q: "Can I get a refund?",                   a: "Yes. Subscriptions include a 14-day money-back guarantee. Contact us within 14 days of purchase and we'll refund you in full." },
          { q: "Is my data safe?",                      a: "Absolutely. Your CVs are private by default and stored securely. We never share your data with third parties." },
        ],
      },
    },

    // ── CV Form ──────────────────────────────────────────────────────────────
    cvForm: {
      tabs: {
        personal:         "Personal",
        experience:       "Experience",
        education:        "Education",
        skills:           "Skills",
        projects:         "Projects",
        languages:        "Languages",
        certifications:   "Certifications",
        templates:        "Templates",
        aiTools:          "AI Tools",
      },
      personal: {
        cvTitle:              "CV Title (internal)",
        cvTitlePlaceholder:   "e.g. Senior Developer CV",
        template:             "Template",
        templateHint:         "— change in the Templates tab",
        fullName:             "Full Name *",
        fullNamePlaceholder:  "Jane Smith",
        jobTitle:             "Job Title *",
        jobTitlePlaceholder:  "Software Engineer",
        email:                "Email",
        emailPlaceholder:     "jane@example.com",
        phone:                "Phone",
        phonePlaceholder:     "+1 555 000 0000",
        location:             "Location",
        locationPlaceholder:  "San Francisco, CA",
        website:              "Website",
        websitePlaceholder:   "https://jane.dev",
        linkedin:             "LinkedIn",
        linkedinPlaceholder:  "linkedin.com/in/jane-smith",
        github:               "GitHub",
        githubPlaceholder:    "github.com/jane-smith",
        portfolio:            "Portfolio",
        portfolioPlaceholder: "https://jane.dev",
        summary:              "Professional Summary",
        summaryPlaceholder:   "Write a brief summary or click 'AI Generate' below...",
        aiGenerateSummary:    "AI Generate Summary",
      },
      experience: {
        position:                "Position",
        company:                 "Company",
        companyPlaceholder:      "Google",
        role:                    "Role",
        rolePlaceholder:         "Senior Engineer",
        startDate:               "Start Date",
        startDatePlaceholder:    "Jan 2022",
        endDate:                 "End Date",
        endDatePlaceholder:      "Present",
        description:             "Description",
        descriptionPlaceholder:  "Describe your responsibilities...",
        achievements:            "Achievements (one per line)",
        achievementsPlaceholder: "Increased performance by 40%\nLed a team of 8 engineers",
        aiGenerate:              "AI Generate",
        addPosition:             "Add Position",
      },
      education: {
        education:              "Education",
        institution:            "Institution",
        institutionPlaceholder: "MIT",
        degree:                 "Degree",
        degreePlaceholder:      "B.Sc.",
        field:                  "Field",
        fieldPlaceholder:       "Computer Science",
        startYear:              "Start Year",
        startYearPlaceholder:   "2018",
        endYear:                "End Year",
        endYearPlaceholder:     "2022",
        grade:                  "Grade / GPA (optional)",
        gradePlaceholder:       "3.9 GPA",
        addEducation:           "Add Education",
      },
      skills: {
        placeholder: "Type a skill and press Enter",
        noSkills:    "No skills added yet",
        tip:         "Tip: Add 10–15 skills relevant to your target role for best ATS results.",
      },
      projects: {
        project:                 "Project",
        name:                    "Project Name",
        namePlaceholder:         "AI CV Generator",
        url:                     "URL (optional)",
        urlPlaceholder:          "https://...",
        description:             "Description",
        descriptionPlaceholder:  "What did this project do? What was your role?",
        technologies:            "Technologies (comma-separated)",
        technologiesPlaceholder: "React, Node.js, PostgreSQL",
        addProject:              "Add Project",
      },
      languages: {
        language:            "Language",
        languagePlaceholder: "English",
        proficiency:         "Proficiency",
        proficiencyOptions:  ["Native", "Fluent", "Advanced", "Intermediate", "Basic"],
        addLanguage:         "Add Language",
      },
      certifications: {
        certification:      "Certification",
        name:               "Certification name",
        namePlaceholder:    "AWS Solutions Architect",
        issuer:             "Issuing organization",
        issuerPlaceholder:  "Amazon Web Services",
        date:               "Date",
        datePlaceholder:    "2024-03",
        url:                "URL (optional)",
        urlPlaceholder:     "https://credly.com/...",
        addCertification:   "Add Certification",
      },
      templates: {
        chooseTemplate:     "Choose a template",
        chooseTemplateHint: "Click a template to apply it instantly. Use the eye icon to preview it full-size before choosing.",
        useTemplate:        "Use this template",
        aboutTemplates:     "About the templates",
        // Descriptions for each template (order matches TEMPLATES array)
        descs: [
          "ATS-friendly",
          "Two-column, indigo",
          "Dark header",
          "Amber accent",
          "Clean & light",
          "Serif, refined",
          "Dark sidebar",
          "Navy & blue",
          "Grey sidebar",
          "Beige & cream",
          "Pale lavender",
          "With portrait",
          "ATS traditional",
          "ATS modern",
        ],
        // Groups for the "About" info box
        groups: [
          { names: "Basic / Classic / Crisp",   desc: "ATS-optimised, single column" },
          { names: "Modern / Slate / Tech",      desc: "Two-column with sidebar" },
          { names: "Executive / Corporate",      desc: "Dark header, formal" },
          { names: "Elegant",                    desc: "Gold accents, serif fonts" },
          { names: "Creative",                   desc: "Amber colour, bold headings" },
          { names: "Minimal",                    desc: "Ultra-light, lots of whitespace" },
          { names: "Warm",                       desc: "Beige & cream tones" },
          { names: "Soft",                       desc: "Pale lavender & rose" },
          { names: "Photo",                      desc: "Includes circular profile photo" },
        ],
      },
      ai: {
        upgradeNotice:           "Upgrade to Premium to unlock AI features: ATS analysis, bullet point generation, and cover letter generation.",
        atsTitle:                "ATS Optimization Check",
        atsDescription:          "Analyze your CV against Applicant Tracking Systems and get a score + improvement suggestions.",
        runAtsCheck:             "Run ATS Check",
        coverLetterTitle:        "Cover Letter Generator",
        coverLetterProBadge:     "Premium",
        coverLetterDescription:  "Generate a personalized cover letter for any job application.",
        generateCoverLetter:     "Generate Cover Letter",
        upgradeToPro:            "Upgrade to Premium",
        premiumBadge:            "Premium",
        premiumRequired:         "This feature is available for Premium subscribers only",
        upgradePremium:          "Upgrade to Premium",
        atsMockSugg1:            "Add relevant industry keywords to pass ATS filters",
        atsMockSugg2:            "Quantify your achievements with numbers and percentages",
        atsMockSugg3:            "Start each bullet point with a strong action verb",
        summaryPremiumLabel:     "AI Generate Summary",
        bulletsPremiumLabel:     "Premium",
      },
      form: {
        requiredFields: "Please fill in the required fields:",
        saveCV:         "Save CV",
      },
      toasts: {
        summaryGenerated: "Summary generated!",
        summaryFailed:    "AI generation failed. Please try again.",
        quotaExceeded:    "OpenAI quota exceeded — check your billing.",
        atsScorePrefix:   "ATS Score:",
        atsFailed:        "ATS check failed. Please try again.",
        enterRole:        "Enter a role title first.",
        bulletsGenerated: "Bullet points generated!",
        bulletsFailed:    "Failed to generate bullet points.",
      },
      validation: {
        titleRequired:    "Title is required",
        nameRequired:     "Name is required",
        jobTitleRequired: "Job title is required",
      },
      import: {
        buttonLabel:       "Import Resume",
        bannerTitle:       "Already have a resume?",
        bannerSubtitle:    "Let AI transform it into a professional, ATS-optimized CV in under 3 minutes.",
        modalTitle:        "Import Your Existing Resume",
        modalSubtitle:     "Upload your CV and let AI extract, improve, and optimize every section.",
        dropzoneTitle:     "Drop your resume here",
        dropzoneOr:        "or",
        dropzoneBrowse:    "browse files",
        dropzoneHint:      "PDF, DOCX, or TXT · Max 5 MB",
        processingTitle:   "Transforming your resume...",
        step1:             "Reading your resume",
        step2:             "Parsing your experience",
        step3:             "Optimizing for ATS",
        successTitle:      "Your resume has been transformed!",
        successBullet1:    "Summary rewritten for impact",
        successBullet2:    "Bullet points improved",
        successBullet3:    "ATS keywords added",
        statExperience:    "experience",
        statExperiences:   "experiences",
        statSkills:        "skills",
        statEducation:     "education",
        statLanguages:     "languages",
        statCerts:         "certifications",
        applyButton:       "Apply to form",
        cancel:            "Cancel",
        tryAgain:          "Try again",
        errorTitle:        "Something went wrong",
        fileTooLarge:      "File too large. Maximum 5 MB.",
        unsupportedType:   "Unsupported format. Use PDF, DOCX, or TXT.",
      },
    },
  },

  // ════════════════════════════════════════════════════════════════════════════
  // FRENCH
  // ════════════════════════════════════════════════════════════════════════════
  fr: {
    nav: {
      features:   "Fonctionnalités",
      pricing:    "Tarifs",
      careers:    "Carrières",
      contact:    "Contact",
      signIn:     "Connexion",
      getStarted: "Commencer",
      myAccount:  "Mon compte",
      myResumes:  "Mes CVs",
    },

    hero: {
      badge:     "Cvixeo — Sois vu. Sois choisi.",
      headline1: "Décrochez l'emploi de vos rêves avec",
      headline2: "CVIXEO",
      subtext:
        "Générez des CV optimisés ATS et professionnels en quelques minutes. Adaptez votre CV à n'importe quelle offre et téléchargez de beaux PDF instantanément.",
      highlights: [
        "ATS-optimisé en un clic",
        "Génération IA de points clés",
        "Export PDF inclus",
      ],
      stats: [
        { value: "10 000+", label: "CV créés" },
        { value: "94 %",    label: "Taux ATS" },
        { value: "3×",      label: "Plus d'entretiens" },
      ],
      ctaPrimary:   "Créer mon CV gratuitement",
      ctaSecondary: "Voir les tarifs",
      noCard:       "Sans carte bancaire · Offre gratuite disponible",
      mock: {
        nav: ["Tableau de bord", "Mes CV", "Modèles", "Paramètres", "Support"],
        stats: [
          { label: "Total CV",    value: "3" },
          { label: "Publiés",     value: "2" },
          { label: "Score ATS",   value: "91 %" },
          { label: "Abonnement",  value: "Pro ✨" },
        ],
        yourCVs:   "Vos CV",
        atsScore:  "Score ATS",
        published: "Publié",
        draft:     "Brouillon",
        newCV:     "Nouveau CV",
      },
    },

    features: {
      sectionLabel: "Fonctionnalités",
      headline:     "Tout ce qu'il vous faut pour décrocher le poste",
      subtext:
        "Du premier jet au PDF final — Cvixeo s'occupe du plus dur pour que vous puissiez vous concentrer sur ce qui compte.",
      items: [
        { title: "Génération IA",                     description: "Décrivez votre parcours et laissez GPT-4 rédiger un CV convaincant et professionnel adapté à votre cible." },
        { title: "Optimisation ATS",                  description: "Scorez votre CV face aux systèmes de suivi des candidatures et obtenez des suggestions précises pour passer les filtres automatiques." },
        { title: "Matching Offre d'emploi",           description: "Collez n'importe quelle offre et obtenez un score de correspondance ainsi qu'une liste d'améliorations pour adapter parfaitement votre CV." },
        { title: "Modèles Élégants",                  description: "Choisissez parmi des modèles conçus par des professionnels. Changez de style instantanément sans perdre vos données." },
        { title: "Export PDF en un clic",             description: "Téléchargez des PDF pixel-perfect parfaits à l'écran et à l'impression. Le plan Pro supprime les filigranes." },
        { title: "Générateur de Lettre de Motivation", description: "Générez automatiquement des lettres de motivation personnalisées adaptées à des offres et entreprises spécifiques." },
      ],
    },

    testimonials: {
      sectionLabel: "Témoignages",
      headline:     "Adopté par des chercheurs d'emploi du monde entier",
      items: [
        { name: "Sarah Chen",      role: "Ingénieure Logiciel chez Google",         avatar: "SC", content: "Cvixeo m'a aidée à décrocher mon emploi de rêve chez Google. L'optimisation ATS a tout changé — mon CV était ignoré avant, mais après les suggestions IA j'ai commencé à recevoir des rappels en quelques jours." },
        { name: "Marcus Johnson",  role: "Product Manager chez Stripe",             avatar: "MJ", content: "J'ai réécrit mon CV 4 fois avant d'essayer Cvixeo. Le matching par offre d'emploi est incroyable — il m'a dit exactement quels mots-clés me manquaient et m'a aidé à personnaliser chaque candidature." },
        { name: "Elena Rodriguez", role: "UX Designer chez Figma",                  avatar: "ER", content: "Le modèle moderne est superbe. Plusieurs recruteurs ont commenté le professionnalisme de mon CV. Le générateur de lettre de motivation m'a économisé des heures par candidature." },
        { name: "David Park",      role: "Data Scientist chez OpenAI",              avatar: "DP", content: "En tant que personne qui n'aime pas écrire, la génération IA était parfaite. J'ai renseigné mon expérience et elle a transformé mes points en descriptions convaincantes et professionnelles." },
        { name: "Priya Patel",     role: "Responsable Marketing chez HubSpot",     avatar: "PP", content: "Chaque centime du plan Pro en vaut la peine. J'ai upgradé 10 minutes après l'essai gratuit — les CV illimités et l'export PDF sont indispensables en recherche active." },
        { name: "James Williams",  role: "Ingénieur Backend chez Vercel",          avatar: "JW", content: "Mon score ATS est passé de 42 à 91 après avoir suivi les suggestions de Cvixeo. J'avais 3 entretiens planifiés une semaine après avoir mis à jour mon CV." },
      ],
    },

    cta: {
      headline:  "Prêt à décrocher l'emploi de vos rêves ?",
      subtext:   "Rejoignez plus de 10 000 professionnels qui ont déjà boosté leur recherche d'emploi avec Cvixeo. Commencez gratuitement, évoluez selon vos besoins.",
      primary:   "Commencer gratuitement",
      secondary: "Voir les offres",
      footnote:  "Sans carte bancaire · Résiliation facile · à partir de 9 €/mois",
    },

    footer: {
      pricing:     "Tarifs",
      features:    "Fonctionnalités",
      careers:     "Carrières",
      signIn:      "Connexion",
      rights:      "Tous droits réservés.",
      product:     "Produit",
      legal:       "Légal",
      about:       "À propos",
      privacy:     "Politique de confidentialité",
      terms:       "Conditions d'utilisation",
      cookies:     "Politique de cookies",
      legalNotice: "Mentions légales",
    },

    pricing: {
      back:             "Retour",
      headline:         "Une tarification simple et transparente",
      subtext:          "Démarrez gratuitement. Essayez 7 jours pour 3,99 €, ou abonnez-vous pour un accès continu.",
      moneyBack:        "Les abonnements incluent une garantie satisfait ou remboursé de 14 jours. Sans condition.",
      faqTitle:         "Questions fréquentes",
      // Noms des cartes
      freeName:         "Gratuit",
      passName:         "Pass 7 Jours",
      monthlyName:      "Premium Mensuel",
      annualName:       "Premium Annuel",
      // Descriptions
      freeDescription:  "Idéal pour démarrer",
      passDescription:  "Accès complet pendant 7 jours",
      monthlyDescription: "Pour les candidats actifs",
      annualDescription:  "Meilleur rapport qualité-prix — −25 %",
      // Fonctionnalités
      freeFeatures: [
        "Créer un CV",
        "Modifier les sections",
        "Modèles de base",
        "Export PDF",
      ],
      passFeatures: [
        "Export PDF sans filigrane",
        "Tous les modèles Premium",
        "Optimisation ATS",
        "Suggestions IA",
        "Personnalisation selon les offres",
        "Génération de lettre de motivation",
        "Import et amélioration de CV",
      ],
      monthlyFeatures: [
        "Toutes les fonctionnalités Gratuites",
        "Optimisation ATS",
        "Suggestions IA avancées",
        "Amélioration automatique de l'expérience",
        "Personnalisation selon les offres d'emploi",
        "Génération de lettre de motivation",
        "Import et amélioration de CV",
      ],
      annualFeatures: [
        "Toutes les fonctionnalités Premium",
        "Économisez 36 €/an par rapport au mensuel",
      ],
      // Boutons CTA
      freeCtaLabel:    "Commencer gratuitement",
      passCtaLabel:    "Accès 7 jours — 3,99 €",
      monthlyCtaLabel: "S'abonner pour 12 €/mois",
      annualCtaLabel:  "S'abonner pour 108 €/an",
      // Badges & labels
      passNew:         "À essayer",
      mostPopular:     "Le plus populaire",
      bestValue:       "Meilleur prix",
      saveBadge:       "−25 %",
      perMonth:        "/mois",
      passOnce:        "paiement unique",
      annualBilledAs:  "facturé 108 €/an",
      previewTitle:    "Ce que vous allez créer",
      plansLabel:      "Voir les offres",
      // Clés conservées pour la compatibilité
      proDescription:  "Pour les candidats sérieux",
      billingMonthly:  "Mensuel",
      billingAnnual:   "Annuel",
      faqs: [
        { q: "Qu'est-ce que le Pass 7 Jours ?",                          a: "Un paiement unique de 3,99 € qui débloque toutes les fonctionnalités Premium pendant 7 jours. Après 7 jours, vous revenez automatiquement au plan Gratuit. Vos CV et données sont toujours conservés." },
        { q: "Puis-je annuler mon abonnement à tout moment ?",           a: "Oui. Annulez votre abonnement Premium à tout moment depuis les paramètres de votre compte. Vous conservez l'accès Premium jusqu'à la fin de votre période de facturation." },
        { q: "Que deviennent mes CV si je passe à la version gratuite ?", a: "Vos CV sont toujours sauvegardés. Avec le plan Gratuit, vous ne pouvez modifier activement qu'1 CV, mais les autres restent accessibles en lecture seule." },
        { q: "Quelle est la différence entre mensuel et annuel ?",        a: "L'abonnement mensuel est à 12 €/mois. L'abonnement annuel est à 9 €/mois facturé 108 €/an — vous économisez 25 % par rapport à la facturation mensuelle." },
        { q: "Quel modèle IA alimente la génération de CV ?",             a: "Nous utilisons Claude d'Anthropic pour toutes les fonctionnalités IA — un modèle de pointe optimisé pour l'écriture professionnelle." },
        { q: "Mes CV sont-ils privés ?",                                  a: "Absolument. Vos CV sont privés par défaut. Vous pouvez choisir de générer un lien partageable, mais rien n'est public sauf si vous le partagez explicitement." },
      ],
    },

    contact: {
      title:    "Contactez-nous",
      subtitle: "Une question ou besoin d'aide ? Nous sommes là pour vous.",
      form: {
        name:               "Votre nom",
        namePlaceholder:    "Marie Dupont",
        email:              "Votre e-mail",
        emailPlaceholder:   "marie@exemple.com",
        subject:            "Sujet",
        subjectPlaceholder: "Comment pouvons-nous vous aider ?",
        message:            "Message",
        messagePlaceholder: "Décrivez votre question ou problème en détail...",
        submit:             "Envoyer le message",
        submitting:         "Envoi en cours…",
        successTitle:       "Message envoyé !",
        successText:        "Nous vous répondrons dans les 24 heures.",
        errorText:          "Une erreur est survenue. Veuillez réessayer.",
      },
      support: {
        heading:       "Nous sommes à votre écoute",
        subheading:    "Notre équipe est dédiée à vous aider à réussir dans votre recherche d'emploi.",
        emailLabel:    "E-mail de support",
        email:         "support@cvixeo.com",
        responseLabel: "Délai de réponse",
        responseTime:  "Sous 24 heures",
        responseNote:  "Lun–Ven, 9h–18h CET",
        reassurance:   "Nous lisons chaque message personnellement et répondons aussi vite que possible. Pas de robots, pas de réponses automatiques — une vraie personne vous répondra toujours.",
      },
      faq: {
        title: "Réponses rapides",
        items: [
          { q: "Comment annuler mon abonnement ?",          a: "Rendez-vous dans Paramètres → Abonnement de votre tableau de bord et cliquez sur Annuler. Vous conservez l'accès Premium jusqu'à la fin de votre période de facturation." },
          { q: "Mon export PDF ne fonctionne pas.",         a: "Assurez-vous que les pop-ups sont autorisés pour ce site. Le PDF s'ouvre dans un nouvel onglet — sauvegardez-le via Ctrl+P → Enregistrer en PDF." },
          { q: "Puis-je obtenir un remboursement ?",        a: "Oui. Les abonnements incluent une garantie satisfait ou remboursé de 14 jours. Contactez-nous dans les 14 jours suivant votre achat et nous vous rembourserons intégralement." },
          { q: "Mes données sont-elles en sécurité ?",      a: "Absolument. Vos CV sont privés par défaut et stockés en toute sécurité. Nous ne partageons jamais vos données avec des tiers." },
        ],
      },
    },

    cvForm: {
      tabs: {
        personal:       "Informations",
        experience:     "Expérience",
        education:      "Formation",
        skills:         "Compétences",
        projects:       "Projets",
        languages:      "Langues",
        certifications: "Certifications",
        templates:      "Modèles",
        aiTools:        "Outils IA",
      },
      personal: {
        cvTitle:              "Titre du CV (interne)",
        cvTitlePlaceholder:   "ex. CV Développeur Senior",
        template:             "Modèle",
        templateHint:         "— changer dans l'onglet Modèles",
        fullName:             "Nom complet *",
        fullNamePlaceholder:  "Marie Dupont",
        jobTitle:             "Intitulé du poste *",
        jobTitlePlaceholder:  "Ingénieur Logiciel",
        email:                "E-mail",
        emailPlaceholder:     "marie@exemple.com",
        phone:                "Téléphone",
        phonePlaceholder:     "+33 6 00 00 00 00",
        location:             "Localisation",
        locationPlaceholder:  "Paris, France",
        website:              "Site web",
        websitePlaceholder:   "https://marie.dev",
        linkedin:             "LinkedIn",
        linkedinPlaceholder:  "linkedin.com/in/marie-dupont",
        github:               "GitHub",
        githubPlaceholder:    "github.com/marie-dupont",
        portfolio:            "Portfolio",
        portfolioPlaceholder: "https://marie.dev",
        summary:              "Résumé professionnel",
        summaryPlaceholder:   "Rédigez un résumé ou cliquez sur « Générer avec l'IA » ci-dessous...",
        aiGenerateSummary:    "Générer avec l'IA",
      },
      experience: {
        position:                "Poste",
        company:                 "Entreprise",
        companyPlaceholder:      "Google",
        role:                    "Intitulé",
        rolePlaceholder:         "Ingénieur Senior",
        startDate:               "Date de début",
        startDatePlaceholder:    "janv. 2022",
        endDate:                 "Date de fin",
        endDatePlaceholder:      "Présent",
        description:             "Description",
        descriptionPlaceholder:  "Décrivez vos responsabilités...",
        achievements:            "Réalisations (une par ligne)",
        achievementsPlaceholder: "Augmentation des performances de 40 %\nEncadrement d'une équipe de 8 ingénieurs",
        aiGenerate:              "Générer avec l'IA",
        addPosition:             "Ajouter un poste",
      },
      education: {
        education:              "Formation",
        institution:            "Établissement",
        institutionPlaceholder: "École Polytechnique",
        degree:                 "Diplôme",
        degreePlaceholder:      "Master",
        field:                  "Domaine",
        fieldPlaceholder:       "Informatique",
        startYear:              "Année de début",
        startYearPlaceholder:   "2018",
        endYear:                "Année de fin",
        endYearPlaceholder:     "2022",
        grade:                  "Mention / Note (facultatif)",
        gradePlaceholder:       "Mention Très Bien",
        addEducation:           "Ajouter une formation",
      },
      skills: {
        placeholder: "Tapez une compétence et appuyez sur Entrée",
        noSkills:    "Aucune compétence ajoutée",
        tip:         "Conseil : Ajoutez 10 à 15 compétences pertinentes pour votre poste cible pour de meilleurs résultats ATS.",
      },
      projects: {
        project:                 "Projet",
        name:                    "Nom du projet",
        namePlaceholder:         "Générateur de CV IA",
        url:                     "URL (facultatif)",
        urlPlaceholder:          "https://...",
        description:             "Description",
        descriptionPlaceholder:  "À quoi servait ce projet ? Quel était votre rôle ?",
        technologies:            "Technologies (séparées par des virgules)",
        technologiesPlaceholder: "React, Node.js, PostgreSQL",
        addProject:              "Ajouter un projet",
      },
      languages: {
        language:            "Langue",
        languagePlaceholder: "Français",
        proficiency:         "Niveau",
        proficiencyOptions:  ["Natif", "Courant", "Avancé", "Intermédiaire", "Notions"],
        addLanguage:         "Ajouter une langue",
      },
      certifications: {
        certification:     "Certification",
        name:              "Nom de la certification",
        namePlaceholder:   "AWS Solutions Architect",
        issuer:            "Organisme délivrant",
        issuerPlaceholder: "Amazon Web Services",
        date:              "Date",
        datePlaceholder:   "2024-03",
        url:               "URL (facultatif)",
        urlPlaceholder:    "https://credly.com/...",
        addCertification:  "Ajouter une certification",
      },
      templates: {
        chooseTemplate:     "Choisir un modèle",
        chooseTemplateHint: "Cliquez sur un modèle pour l'appliquer instantanément. Utilisez l'icône œil pour prévisualiser en grand avant de choisir.",
        useTemplate:        "Utiliser ce modèle",
        aboutTemplates:     "À propos des modèles",
        descs: [
          "Compatible ATS",
          "Deux colonnes, indigo",
          "En-tête sombre",
          "Accent ambre",
          "Épuré & léger",
          "Serif, raffiné",
          "Barre latérale sombre",
          "Marine & bleu",
          "Barre grise",
          "Beige & crème",
          "Lavande pâle",
          "Avec portrait",
          "ATS traditionnel",
          "ATS moderne",
        ],
        groups: [
          { names: "Basic / Classic / Crisp", desc: "ATS-optimisé, colonne unique" },
          { names: "Modern / Slate / Tech",   desc: "Deux colonnes avec barre latérale" },
          { names: "Executive / Corporate",   desc: "En-tête sombre, formel" },
          { names: "Elegant",                 desc: "Accents dorés, polices serif" },
          { names: "Creative",                desc: "Couleur ambre, titres en gras" },
          { names: "Minimal",                 desc: "Ultra-léger, beaucoup d'espace" },
          { names: "Warm",                    desc: "Tons beige et crème" },
          { names: "Soft",                    desc: "Lavande pâle et rose" },
          { names: "Photo",                   desc: "Inclut une photo de profil circulaire" },
        ],
      },
      ai: {
        upgradeNotice:          "Passez au Premium pour débloquer les fonctionnalités IA : analyse ATS, génération de points clés et lettre de motivation.",
        atsTitle:               "Vérification ATS",
        atsDescription:         "Analysez votre CV face aux systèmes de suivi des candidatures et obtenez un score + des suggestions d'amélioration.",
        runAtsCheck:            "Lancer la vérification ATS",
        coverLetterTitle:       "Générateur de lettre de motivation",
        coverLetterProBadge:    "Premium",
        coverLetterDescription: "Générez une lettre de motivation personnalisée pour chaque candidature.",
        generateCoverLetter:    "Générer la lettre",
        upgradeToPro:           "Passer au Premium",
        premiumBadge:           "Premium",
        premiumRequired:        "Cette fonctionnalité est réservée aux abonnés Premium",
        upgradePremium:         "Passer au Premium",
        atsMockSugg1:           "Ajoutez des mots-clés sectoriels pour passer les filtres ATS",
        atsMockSugg2:           "Quantifiez vos réalisations avec des chiffres et des pourcentages",
        atsMockSugg3:           "Commencez chaque point par un verbe d'action fort",
        summaryPremiumLabel:    "Générer avec l'IA",
        bulletsPremiumLabel:    "Premium",
      },
      form: {
        requiredFields: "Veuillez remplir les champs obligatoires :",
        saveCV:         "Enregistrer le CV",
      },
      toasts: {
        summaryGenerated: "Résumé généré !",
        summaryFailed:    "La génération IA a échoué. Veuillez réessayer.",
        quotaExceeded:    "Quota OpenAI dépassé — vérifiez votre facturation.",
        atsScorePrefix:   "Score ATS :",
        atsFailed:        "La vérification ATS a échoué. Veuillez réessayer.",
        enterRole:        "Saisissez d'abord un intitulé de poste.",
        bulletsGenerated: "Points clés générés !",
        bulletsFailed:    "Échec de la génération des points clés.",
      },
      validation: {
        titleRequired:    "Le titre est requis",
        nameRequired:     "Le nom est requis",
        jobTitleRequired: "L'intitulé du poste est requis",
      },
      import: {
        buttonLabel:       "Importer mon CV",
        bannerTitle:       "Vous avez déjà un CV ?",
        bannerSubtitle:    "Laissez l'IA le transformer en CV professionnel optimisé ATS en moins de 3 minutes.",
        modalTitle:        "Importer votre CV existant",
        modalSubtitle:     "Téléchargez votre CV et laissez l'IA extraire, améliorer et optimiser chaque section.",
        dropzoneTitle:     "Déposez votre CV ici",
        dropzoneOr:        "ou",
        dropzoneBrowse:    "parcourir les fichiers",
        dropzoneHint:      "PDF, DOCX ou TXT · 5 Mo max",
        processingTitle:   "Transformation de votre CV...",
        step1:             "Lecture de votre CV",
        step2:             "Analyse de votre expérience",
        step3:             "Optimisation ATS",
        successTitle:      "Votre CV a été transformé !",
        successBullet1:    "Résumé réécrit pour l'impact",
        successBullet2:    "Points clés améliorés",
        successBullet3:    "Mots-clés ATS ajoutés",
        statExperience:    "expérience",
        statExperiences:   "expériences",
        statSkills:        "compétences",
        statEducation:     "formations",
        statLanguages:     "langues",
        statCerts:         "certifications",
        applyButton:       "Appliquer au formulaire",
        cancel:            "Annuler",
        tryAgain:          "Réessayer",
        errorTitle:        "Une erreur est survenue",
        fileTooLarge:      "Fichier trop volumineux. Maximum 5 Mo.",
        unsupportedType:   "Format non supporté. Utilisez PDF, DOCX ou TXT.",
      },
    },
  },
} as const;
